### ISSUE TITLE
Change focus on error when submitting a new license

### ISSUE THREAD

**Issue by goneall** [spdx/spdx-online-tools#109]
When a field fails validation, the error is displayed at the top of the page.  If you are scrolled at the bottom, you don't see the error message.

Scrolling to the top of the page where the error is would highlight the error and solve the issue.

It would also help to highlight the field in error in red.

**Comment by ithompson4** [comment]
I would like to work on this. It would be a huge help if I you could let me know the basic business rules/validation the system enforces when submitting a new license. That is what are the basic data entry rules for each new license data entry field. Then I could submit new licenses that were accepted, and ones that I know will be correctly rejected.Thank you.

**Comment by rtgdk** [comment]
@ithompson4 The field validation is already done, both in backend(Python view function) and frontend(Javascript check on submit). The javascript errors are shown at the top of the page, so if the form is long, the user while clicking submit would be at the bottom at the page. The task is to take the user to the top of the page so that he/she can see what the error is.

**Comment by rtgdk** [comment]
I think @Ugtan opened a PR for that. (@Ugtan you didn't mention that you would be working on this issue before opening a PR)

**Comment by Ugtan** [comment]
@rtgdk Sorry about that. I actually solved it during the proposal phase but i forgot to commit the changes. And, i didn't even realised that someone commented as @ithompson4 commented a few minutes before i pushed my changes. I will ensure to comment from the next time.
