### ISSUE TITLE
add new question to submit new license form

### ISSUE THREAD

**Issue by jlovejoy** [spdx/spdx-online-tools#118]
can we add a new question to the submit new license form?
I'd like to add it below the OSI Status question. the question text would be:

_FSF free/libre?_

Pop-up text would say: "Is the license is considered free by the FSF  according to this page: https://www.gnu.org/licenses/license-list.en.html

Options for answering would be a drop-down with yes/no/I don't know

@swinslow or @bradleeedmondson - can you have a look at wording?

**Comment by goneall** [comment]
Just FYI - The LicenseListPublisher currently scrapes the HTML from the FSF website and attempts to match licenses.  If we decide to add an FSF license with a "Y", we need to make sure it is consistent with the FSF website or the LicenseListPublisher will need to be updated to override the information in the FSF website.

**Comment by goneall** [comment]
Two detail questions:
- Should this be required?
- Should we have a default value?

**Comment by jlovejoy** [comment]
> The LicenseListPublisher currently scrapes the HTML from the FSF website and attempts to match licenses. If we decide to add an FSF license with a "Y", we need to make sure it is consistent with the FSF website or the LicenseListPublisher will need to be updated to override the information in the FSF website.

oh, I did not know that. So that step is at the point when we publish the license list, not part of the submission process?

**Comment by jlovejoy** [comment]
if we can automate this (or already have), then maybe no need for this question. 
it's not like OSI, where sometimes things are in-flight and the submitter is the best person to know that.

**Comment by goneall** [comment]
> So that step is at the point when we publish the license list, not part of the submission process?

Correct.  There actually isn't a way to specify FSF Free in the license XML document today.

**Comment by goneall** [comment]
> if we can automate this (or already have), then maybe no need for this question.

I guess if we asked the question, we may end up being in the middle between a requester and the FSF as to the FSF free status.  It is more of a process question, but I'm leaning towards leaving it in the automated state and not ask the question.  If someone wants to update the FSF free status they can work directly with the FSF since the FSF maintains a web page with that information.

There is one more consideration, which is that the code that scrapes the HTML isn't reliable.  We've asked the FSF to provide a more reliable means of updating the status and to date they haven't done anything that I am aware of.

Right now, we just fix the scraper if an issue is raised.

**Comment by jlovejoy** [comment]
@goneall - agreed, relying on scraping/automating seems like the best way to go. And better effort spent trying to get FSF to improve code we are scraping!

I think we can close this, then
