### ISSUE TITLE
License submittal fails for close match if an existing license submittal exists for the same license short ID

### ISSUE THREAD

**Issue by goneall** [spdx/spdx-online-tools#137]
Error is due to multiple license submittals being returned from a query based on the license short identifier

**Comment by Ugtan** [comment]
@goneall One way to solve this would be to make the license short identifier unique which might be a good way to ensure a single value is returned everytime. This would also prompt user to use a different short identifier. Since we are not concerned with the actual identifier but the contents of the license, the spdx license match will still report the results irrespective of the name of the identifier. Also, I remember we had a talk via email about the same and you mentioned `[G.O.] Good point.  The specification does require the license ID’s to be unique.  Something we could check for.  The names should be unique (alther it isn’t specified).`. Let me know your thoughts regarding the same. Thanks

**Comment by goneall** [comment]
> One way to solve this would be to make the license short identifier unique

This would work for the new license requests.  But if we are making an issue to update an existing license in the case when there is a close match and the user selects the licenses should be the same, we will have more than one request for the same license ID.

**Comment by Ugtan** [comment]
> This would work for the new license requests. But if we are making an issue to update an existing license in the case when there is a close match and the user selects the licenses should be the same, we will have more than one request for the same license ID.

There should be atleast a field that should be uniquely identified in order to have multiple requests with the same license ID. But if that's the case, using id or pk of a license request might work.
