### ISSUE TITLE
Dockerize spdx-online-tools

### ISSUE THREAD

**Issue by Prodyte** [spdx/spdx-online-tools#183]
Dockerizing will enable a smoother flow of execution and development.

**Comment by Prodyte** [comment]
Hey @rtgdk @goneall can you assign me this issue?

**Comment by rtgdk** [comment]
@Prodyte You don't need approval to work on issues raised by you. Nevertheless, I'll assign it to you.

**Comment by rtgdk** [comment]
@Prodyte My bad. This project is already proposed in the Community Bridge program ideas - https://wiki.spdx.org/view/CommunityBridge/CommunityBridge_ProjectIdeas
and is scheduled to be done during the program. Your PR won't be merged for this issue since it will require some communication with mentors and is a summer-long project.
You can still work on the deployment structure yourself and create your Community Bridge proposal on that.

**Comment by kmehant** [comment]
@rtgdk 
Community Bridge selections were out and found that this project will no longer be part of the community bridge program. So I guess we should unlock this issue. 
Thank you.

**Comment by rtgdk** [comment]
@kmehant @Prodyte You are free to work on this since it didn't get selected for the Community Bridge program.
Comment below if you wish to work on this so other people can pick up another issues.
Thanks!

**Comment by kmehant** [comment]
@rtgdk sure shall I take up this?

**Comment by rtgdk** [comment]
@kmehant Sure! 😄
