### ISSUE TITLE
Test/determine whether the SPDX online tools can run in a clustered environment

### ISSUE THREAD

**Issue by goneall** [spdx/spdx-online-tools#195]
To be supported in a clustered environment, there are a few things we should validate:

- Is there any persistent data stored outside the SQL database which would need to be shared?
- Are there any concurrency transaction isolation issues if we were to have more than one online tools instance accessing the same database?
- Any other issues which would cause a clustered environment to fail?

**Comment by goneall** [comment]
@rtgdk Are you aware of any issues?

**Comment by rtgdk** [comment]
@goneall Apart from sql and redis, we store the file uploaded and converted in "/media" directory. This might cause issue when running instances on different nodes. We can also use s3 to store the files. I also found one more issue related to /media files in docker : https://stackoverflow.com/questions/58552837/maintain-the-media-files-after-build-with-docker-container-django.
I am not sure whether this will be an issue since /media are temporary files (files uploaded by user, or files converted and served to the user for download)

**Comment by rtgdk** [comment]
I am not aware of any concurrency transaction issues in the online tools. But this can be tested once we have the application up and runnning.

**Comment by goneall** [comment]
Perhaps we should start simple by having a single instance running to avoid any possible issues with the storage.  Once we get that working, we can explore multiple instances.
