### ISSUE TITLE
How do we "authorize" users to archive license requests?

### ISSUE THREAD

**Issue by goneall** [spdx/spdx-online-tools#237]
The archive license requests is only allowed for authorized users.

Since the logins are now done by Github, creating a superuser for this function won't work.

How do we enable an existing user to be authorized for these functions?

**Comment by goneall** [comment]
I found that code that checks the permissions at: 

https://github.com/spdx/spdx-online-tools/blob/415fcecd01a9fa08036dbe53ad392c476de59c4c/src/app/utils.py#L56

When I use the production instance at http://13.57.134.254/app/ my username is goneall9ea2cb6faa12445f and I am authorized.

On the test instance at http://52.32.53.255/app, my username is goneall and I am not authorized.

**Comment by rtgdk** [comment]
@goneall It checks if the user has collaboration access to https://github.com/spdx/tools-python/. Can you check your github login username from superadmin on the test instance (Not sure if `goneall9ea2cb6faa12445f` is github login username or django db username)? I am not a superadmin so I couldn't check. (Also, maybe we need to change the repo to https://github.com/spdx/license-list-XML?)

Also, I think we need to change who can archive license requests feature - the person who submitted the requests, and spdx team members. I think we can assign a role to spdx team members and that should be checked instead of collabooration access. Django provides RBAC - but some super admin has to assign the roles (manual process).

**Comment by goneall** [comment]
After reading through the code, it looks like the fix for authorizing the archive function was inside the post code.  I submitted PR #237 to resolve.
