### ISSUE TITLE
URL's are limited to only one even though the UI accepts multiple

### ISSUE THREAD

**Issue by goneall** [spdx/spdx-online-tools#249]
The submit_new_license form accepts multiple source / URL in the UI by clicking on the "add a source".

This information is not included in the database nor the issue.

The form looks like it is just a simple charfield: https://github.com/spdx/spdx-online-tools/blob/6599e81df10f3131f6171c99fc83fee3a8bb00a8/src/app/forms.py#L81

Looking at the views, it simply stores the charfield as a single element of a list: https://github.com/spdx/spdx-online-tools/blob/6599e81df10f3131f6171c99fc83fee3a8bb00a8/src/app/views.py#L112

**Comment by goneall** [comment]
I could really use some help on this one from someone more experienced in Django.  Is there a different field that should be used?

**Comment by rtgdk** [comment]
@goneall A simple way would be to use a TextField instead of a CharField and add all source urls either comma-separated or json formatted(preferred). 
If you face any difficulty, I can work on this as soon as I get some time(too busy with work). Will raise a PR by end of this week.

**Comment by goneall** [comment]
@rtgdk Did a bit of work on this without much progress.

I couldn't find a TextField in the Django form package/file.  I looked through the source code for a field which would work and didn't find anything that would work for multiple values.

I was able to get the request.POST object to include all the values, but I wasn't able to access it from the Python side.

Here's the output from the debugger using the latest update from PR #248 

```
(Pdb) request.POST
<QueryDict: {u'osiApproved': [u'Approved'], u'userEmail': [u'gary@sourceauditor.com'], u'sourceUrl': [u'http://sourcee1.com', u'http://source2.om'], u'text': [u'text'], u'licenseAuthorName': [u'Gary'], u'comments': [u'Comment'], u'exampleUrl': [u'http://example1.com', u'http://example2.com'], u'shortIdentifier': [u'testid'], u'submit': [u''], u'csrfmiddlewaretoken': [u'1Pp5eAkudgUS1HJgAJ0AkZ1uZxB0FoicHQL1vc66CUhWuFDJyumxqt3qviMLV8Hn'], u'licenseHeader': [u'header'], u'fullname': [u'Test License [Please Ignore]']}>
(Pdb) request.POST['sourceUrl']
u'http://source2.om'
(Pdb)
```

Notice that the request.POST shows a `sourceUrl` value of an array, but when I accessed the single value, it only picked up the first string and didn't return the array.

I was thinking we could just pick the data out of request.POST directly if there isn't a DJango form field which supports this, but I couldn't access the array.

Let me know any thoughts.

**Comment by rtgdk** [comment]
@goneall There's a TextField in django models https://docs.djangoproject.com/en/3.1/ref/models/fields/#textfield. For storing all the urls as list/json encoded, we would have to change the model field first. For django forms, suprisingly I couldn't find corresponsing textfield. The docs says that since Charfield and TextField differ only in the ui widget they show (for TextField it's textarea, for CharField it's just an input), there's no extra field for text type.
So, we can go with the current design of the forms - We just to retrieve the list of values in POST request (There's should be a way to either append the post request with all the field either through javascript) Or we can go with MultiValueField in django forms- https://docs.djangoproject.com/en/3.1/ref/forms/fields/#multivaluefield.

Let me just wrap my work. I'll be able to commit this by this week's end if you are not able to.

**Comment by goneall** [comment]
I think I figured out how to get multiple values - `request.POST` is a type `QueryDict` which has a method to return a list.  I updated the views.py file to call `request.POST.getlist('sourceUrl')` but ran into another issue.  I'll continue working on it and hope to have an update soon.

**Comment by goneall** [comment]
Resolved with commit https://github.com/spdx/spdx-online-tools/pull/248/commits/d2f7d095217ea874bde226f0d26fd5dac8f7766c in PR #248
