### ISSUE TITLE
Use the scancode toolkit for check license function

### ISSUE THREAD

**Issue by techytushar** [spdx/spdx-online-tools#27]
As suggested by @pombredanne using the scancode-toolkit for check license function would be better, instead of using the Java function and it is also in the TODO list. @goneall  @rtgdk Please give your views

**Comment by goneall** [comment]
I don't believe that Scancode complies with the SPDX [license matching guidelines](https://spdx.org/spdx-license-list/matching-guidelines).  Since this is an SPDX tool, the license matching should comply with the guidelines.  If Scancode does not comply, the Java tools should be used to fully check if license text matches. 

There is, however, a performance issue with any tool fully complying with the license matching guidelines especially when used to check against a large number of possible license matches.

Using the Scancode to narrow down the possible license matches and then calling the Java code could improve the performance while retaining the accuracy of implementing the matching guidelines.

There is an issue tracking the performance of the Java tools here: https://github.com/spdx/tools/issues/151
