### ISSUE TITLE
Transforming samples from spdx-spec via tools.spdx.org/app/convert lead to discrepancies

### ISSUE THREAD

**Issue by MarkusTe** [spdx/spdx-online-tools#307]
Hello,

that looks strange.

1. I've taken the [sample files of the spec](https://github.com/spdx/spdx-spec/tree/development/v2.2.1/examples).
2. Then I've [transformed](https://tools.spdx.org/app/convert/) them, e.g., YAML to RDF/XML.
3. Then compared the original with the transformation, e.g., sample RDF/XML to the transformed RDF/XML.
4. In all cases, the originals differ from the transformed files. And sizes differ as well, some of them quite a bit.

Especially transformations from any format to RDF/XML seem to lead to much larger results.

- 211KB - Original RDF
- 333KB - JSON to RDF
- 333KB - Tag to RDF
- 337KB - YAML to RDF
- 338KB - XML to RDF

Transformations from any format to SPDX seem to be quite consistent but lines are not in the same order.

In some cases the same sorting/sequence of data in each "block" would help, e.g., always alphabetically.

"License 1 or License 2" is same as "License 2 or License 1"

"ABC
DEF"
is same as
"DEF
ABC"

I would have hoped (yeah, blind wish) that transforming the different formats among each other would always lead to the same binary-identical results. But more importantly no information should get lost or wrong when applying a transformation.

Many gtx
Markus

**Comment by goneall** [comment]
@MarkusTe Thanks for logging the issue.

The RDF/XML format does not preserve any order.  This is both an issue with the [RDF/XML spec](https://www.w3.org/TR/rdf-syntax-grammar/) and the underlying [Jena RDF](https://jena.apache.org/) code.  I would not expect any order preservation for RDF/XML since it would require significant effort.  If anyone is interested in researching this further and proposing any solutions,  the code is open source at https://github.com/spdx/spdx-java-rdf-store.

Things are a bit more hopeful for the YAML, XML and JSON formats which use the [spdx-java-jackson-store](https://github.com/spdx/spdx-java-jackson-store) code which supports sorting of properties.  The [PropertyComparator.java](https://github.com/spdx/spdx-java-jackson-store/blob/master/src/main/java/org/spdx/jacksonstore/PropertyComparator.java) is used to sort. If you think a specific ordering is missing for the JSON or YAML formats, please add an issue to the spdx-jackson-store issues list or (better yet) add a pull request.

A couple other expected differences for transformations are the use of generated anonymous identifiers in the creation of these files.  These identifiers are only valid within the scope of the SPDX document and are not guaranteed to be the same.

It is a bit concerning that the size is different - I could explain minor differences in size, but if there are large differences I would suspect a bug. One way to find out if there is a bug would be to run the [comparison](https://tools.spdx.org/app/compare/) between the different formats.  If they don't come out the same, please add an issue with the details.

**Comment by MarkusTe** [comment]
The comparison seems to show no relevant difference in content. So the difference in size cannot be explained, at least by me.
We aim to use YAML a lot, so maybe I will raise an improvement issue for Jackson.

**Comment by goneall** [comment]
@MarkusTe Thanks for doing the comparisons.  Based on the results, I wouldn't worry about the difference in size.

Yes - please suggest any improvements to the Jackson store used for YAML serialization - that would benefit the JSON and XML formats as well.

**Comment by goneall** [comment]
I'm going to go ahead and close this issue since the improvements to the jackson store are now deployed
