### ISSUE TITLE
md5 not supported in JSON validator

### ISSUE THREAD

**Issue by elear** [spdx/spdx-online-tools#332]
It's in the schema, but not recognized as an enumeration.  I'd submit a PR but I don't know which file to look at.

**Comment by goneall** [comment]
It looks like MD5 is supported in the schema:

https://github.com/spdx/spdx-spec/blob/2be70fcdf33c7e54290c17924a2b471d87afa0f0/schemas/spdx-schema.json#L165

Could this be an issue of the enum being case sensitive?

@elear If it is not due to case sensitive enums, you could upload an example file that is not validating?

**Comment by elear** [comment]
My apologies.  It is indeed a case problem.
