### ISSUE TITLE
Update versions from the packages

### ISSUE THREAD

**Issue by goneall** [spdx/spdx-online-tools#420]
Currently, the Java tools and NTIA Conformance checker versions displayed on the About page are hard-coded.

We could obtain these versions from the packages themselves.

Originally suggested by @rtgdk https://github.com/spdx/spdx-online-tools/pull/419#discussion_r1066020825

**Comment by HirumalPriyashan** [comment]
Hi @goneall, I would like to work on this issue and hoping to clarify few things before starting.

Currently, `tool.jar` is manually uploaded and so does the version of it manually updated. Since this `Jar` file is the only relation to `Java Tools`, I think we need to extract version through that i.e. `pom.xml`. 
May I have your thoughts on that or is there any viable alternative?
Thanks.

**Comment by goneall** [comment]
Thanks @HirumalPriyashan for looking into this issue.

For the tools.jar, there is a command line option to get the version but in looking at the code there isn't an equivalent API.  You could capture the output of the command line but you would need to trim off the extra version information printed.  See https://github.com/spdx/tools-java/blob/4e1908d1ff76d4b9aa90af3c3536cf505303b094/src/main/java/org/spdx/tools/Main.java#L57 for the implementation.

A better approach would be to implement an API in the Java tools to get the version information.  An API exists for the Library and License List versions, just not the tools version itself.

**Comment by HirumalPriyashan** [comment]
Thanks, for the reply.
I have used the first approach and sent a PR addressing this, since second one requires a release of Java Tools.
But would like to go through the second approach, since it is much cleaner.
Shall I create an issue in https://github.com/spdx/tools-java to track and address changes in there?

**Comment by goneall** [comment]
> I have used the first approach and sent a PR addressing this, since second one requires a release of Java Tools.

Thanks!

> Shall I create an issue in https://github.com/spdx/tools-java to track and address changes in there?

Yes
