### ISSUE TITLE
"Invalid license expression. Expecting more operands." for licenses like ASL 2.0 with multiple words

### ISSUE THREAD

**Issue by juspence** [spdx/spdx-online-tools#474]
We see the below error when submitting license identifiers with spaces:
```
Error! Analysis exception processing SPDX file:
Error parsing JSON field for ID SPDXRef-a418e57b-2990-4038-b22f-a7224c990647:
Invalid license expression. Expecting more operands.
License expression: 'LGPLV2+ AND BSD AND PUBLIC DOMAIN'
```

Note values like ```PUBLIC DOMAIN``` or ```ASL 2.0``` are extremely common in the public Fedora / CentOS project data, for example:
https://centos.pkgs.org/8/centos-appstream-x86_64/ruby-devel-3.0.2-140.module_el8.5.0+991+268c5cd9.x86_64.rpm.html#view_packages_info

LICENSE headers on many different RPMs use "identifiers" like this, which are actually multiple words. The validator seems to break because it expects an operator (AND, OR, WITH) after any space, and does not support multi-word identifiers.

It would be better if the validator could build license identifiers from multiple words, like below:
1. Split the license string on spaces
2. Take the first token in the string, and the first token after an operator, as the start of a new license identifier
3. If the next token IS NOT an operator, add the next token to the current license identifier
4. If the next token IS an operator, stop building the current license identifier (it's complete)
5. Repeat above until reaching the end of the string

**Comment by goneall** [comment]
The validator follows the specific syntax and rules as defined by the [SPDX Spec Annex D](https://spdx.github.io/spdx-spec/v2.3/SPDX-license-expressions/).

Rather than changing the tool to validate against something other than the spec, I would suggest opening an issue against the spec to handle the situation described.  If the spec is updated, we'll update the validation accordingly.
