### ISSUE TITLE
https://tools.spdx.org/ seems to be down

### ISSUE THREAD

**Issue by sschuberth** [spdx/spdx-online-tools#478]
Is there a known outage, @goneall?

**Comment by goneall** [comment]
@sschuberth - yes - I got an alert last night.  This is a repeat of issue #435

I wasn't able to reboot since I was traveling.  I rebooted it this morning (stopping by a coffee shop with internet connection on a drive).

BTW - we're looking for another volunteer (or two) to help maintain the server.  It basically just needs a reboot - a 10 minute process.

I plan to upgrade the server when I do the next update - hopefully in the net week or two.

**Comment by sschuberth** [comment]
> I rebooted it this morning (stopping by a coffee shop with internet connection on a drive).

Thanks!
