### ISSUE TITLE
Add edit xml button on license requests page 

### ISSUE THREAD

**Issue by techytushar** [spdx/spdx-online-tools#76]
We can add a `Edit XML` button besides the `Download XML` button on the `license_requests` page which would open the XML file in the editor so that the user can edit it further. Will that be a good idea @goneall @rtgdk

**Comment by goneall** [comment]
@rtgdk I need to go back through the workflow.  There are 2 scenarios, one where a member of the legal team is submitting a license request and another submitter when someone outside the legal team is submitting.  For the former, I think having a button to go directly to the XML editor would make the workflow easier and faster.  For the latter, they probably would not edit the XML since they would not be familiar with the format.

@jlovejoy As someone who has submitted a few licenses, what do you think?

**Comment by jlovejoy** [comment]
so are you thinking to add a "edit XML" button on this page: http://13.57.134.254/app/license_requests/ (in the list) or on the specific page for the license itself? i.e., http://13.57.134.254/app/license_requests/11/

Would this "edit xml" button take you automatically to the XML Editor tool and functionality?

**Comment by tjasmith** [comment]
@techytushar @goneall @jlovejoy 
Is it Ok if I work on this issue/enhancement? Or do you have a more pressing and important issue which you want me to work on?

**Comment by techytushar** [comment]
@jlovejoy Yes, the idea is to display the `Edit XML` button on this page: http://13.57.134.254/app/license_requests/11/ which will take the user to the XML Editor with the text of that license prefilled.

**Comment by goneall** [comment]
@tjasmith I think this would be a good enhancement to work on

**Comment by tjasmith** [comment]
@goneall. On it !

**Comment by goneall** [comment]
@tjasmith contributed a solution with PR #79 which has been deployed
